project:
  type: book
  
book:
  title: "Structural Bioinformatics 101"
  author: "Paulyna Magaña"
  date: "06/06/2025"
  search: true
  repo-url: https://github.com/paulynamagana/structural-bioinformatics-101
  sharing: [twitter, linkedin]
  downloads: [pdf]
  
  sidebar:
      style: docked
      collapse-level: 4
      search: true

  navbar:
    background: primary
    collapse-level: 4

  page-navigation: true

  
  chapters:
    - index.qmd
    - introduction.qmd 
    - python-fundamentals.qmd
    
  page-footer:
    left: "Copyright 2025, Paulyna Magaña"

bibliography: references.bib

format:
  html:
    number-depth: 4
    theme:
      light: flatly
      dark: darkly
    code-overflow: wrap
    respect-user-color-scheme: true
    
  pdf: 
    documentclass: scrbook
    fontfamily: libertinus
    number-depth: 1