project:
  type: website
  output-dir: docs

website:
  title: "structural-bioinformatics-101"
  page-footer: "Copyright 2025, Paulyna Magaña" 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        menu:
          - text: Code
            href: https://github.com/paulynamagana/structural-bioinformatics-101
  sidebar:
    style: "docked"
    search: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
github-repo: 
editor: visual



